# Generated by Django 4.0.6 on 2024-05-05 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_alter_teacher_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subject',
        ),
    ]
